[package]
name = "hyper-native-tls"
version = "0.2.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
exclude = ["test/*"]
license = "MIT/Apache-2.0"
description = "native-tls support for Hyper"
repository = "https://github.com/sfackler/hyper-native-tls"
documentation = "https://docs.rs/hyper-native-tls/0.2.0/hyper_native_tls"
readme = "README.md"

[dependencies]
antidote = "1.0"
native-tls = { git = "https://github.com/segfault87/rust-native-tls.git", default-features = false, features = ["force_openssl"] }
hyper = "0.10"

[features]
force_openssl = []

[dev-dependencies]
openssl = "0.9"
hyper-openssl = "0.2"
